---
- hosts: all
  become: true
  gather_facts: false
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    docker_images:
      - chanduj/traveltrails_frontend:latest
      - chanduj/traveltrails_backend:latest
      - mongo:4.4.25
  tasks:
    - name: Install Docker packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      tags:
        - docker

    - name: Add Docker official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker


    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
        state: present
      tags:
        - docker

    - name: Update apt packages
      apt:
        update_cache: yes
      tags:
        - docker

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      tags:
        - docker

    - name: Ensure Docker is started and enabled at boot
      systemd:
        name: docker
        enabled: yes
        state: started
      tags:
        - docker

    - name: Add remote "ubuntu" user to "docker" group
      user:
        name: "ubuntu"
        group: "docker"
        append: yes
      tags:
        - docker

    - name: Pull required Docker images
      docker_image:
        name: "{{ item }}"
        source: pull
        state: present
      loop: "{{ docker_images }}"
      tags:
        - docker

    - name: Create MongoDB volume
      docker_volume:
        name: mongo-data
      tags:
        - docker

    - name: Create Docker network
      docker_network:
        name: "{{ docker_network }}"
        state: present
      tags:
        - docker

    - name: Run MongoDB container
      docker_container:
        name: mongo
        image: mongo:4.4.25
        state: started
        ports:
          - "27017:27017"
        restart_policy: always
        networks:
          - name: "{{ docker_network }}"
        volumes:
          - "mongo-data:/data/db"
      tags:
        - docker

    - name: Run backend container
      docker_container:
        name: backend
        image: chanduj/traveltrails_backend:latest
        state: started
        restart_policy: always
        networks:
          - name: "{{ docker_network }}"
        ports:
          - "4000:4000"
        links:
          - "mongo:mongo"
      tags:
        - docker

    - name: Run frontend container
      docker_container:
        name: frontend
        image: chanduj/traveltrails_frontend:latest
        state: started
        restart_policy: always
        networks:
          - name: "{{ docker_network }}"
        ports:
          - "3000:3000"
        links:
          - "backend:backend"
      tags:
        - docker
