---
- hosts: all
  become: true
  gather_facts: false
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    docker_images:
      - chanduj/traveltrails_frontend:latest
      - chanduj/traveltrails_backend:latest
      - mongo:4.4.25
    docker_network: traveltrails_network
  tasks:
    - name: Install Docker packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
      tags:
        - docker

    - name: Add Docker official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker


    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
        state: present
      tags:
        - docker

    - name: Update apt packages
      apt:
        update_cache: yes
      tags:
        - docker

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      tags:
        - docker

    - name: Ensure Docker is started and enabled at boot
      systemd:
        name: docker
        enabled: yes
        state: started
      tags:
        - docker

    - name: Add remote "ubuntu" user to "docker" group
      user:
        name: "ubuntu"
        group: "docker"
        append: yes
      tags:
        - docker

    - name: Install docker-compose
      remote_user: ubuntu
      get_url: 
        url : https://github.com/docker/compose/releases/download/v2.28.1/docker-compose-linux-x86_64   
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Copy Docker Compose file to remote server
      copy:
        src: /opt/jenkins-slave/workspace/TravelTrails/TravelTrails/docker-compose-remote.yml
        dest: /usr
      tags:
        - docker

    - name: Run Docker Compose up
      command: docker-compose -f docker-compose-remote.yml up -d
      args:
        chdir: /usr
      tags:
        - docker