# backend
# Use an official Node.js runtime as a parent image
FROM node:22

# Set the working directory to the root of the backend folder in the container
WORKDIR /

# Install dependencies
RUN npm install

# Expose the application port
EXPOSE 4000

# Command to run the application
CMD ["npm", "start"]
