version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "5000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/travelTrails
      - SECRET=qweuiopjklasdfbnmzxcvasdfghjkl
      - PORT=4000
    depends_on:
      - mongo
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - my_network

  mongo:
    image: mongo:4.4.25
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my_network

volumes:
  mongo-data:

networks:
  my_network:
