# frontend
# Use an official Node.js runtime as a parent image
FROM node:22

# Install dependencies
RUN npm install

# Expose the application port
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]
